name: CI checks

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x, 17.x, 18.x, 19.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Unit Testing
        run: npm test
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.node-version == '19.x' }}
        uses: codecov/codecov-action@v3
        with:
          flags: ecma-262-regexp-parser
          directory: ./packages/ecma-262-regexp-parser/.coverage
          token: ${{ secrets.CODECOV_TOKEN }}
